### MERGING THE TWO DATAFRAMES ....

In [64]:
import numpy as np 
import pandas as pd

In [65]:
emp={
    'employee_id':[1,2,3,4,5],
    'name':['Chetan','Prerna','Lokendra','Nitin','Pranav'],
    'department':['Hr','IT','Finance','Sales','Marketing']
}

sal={
    'employee_id':[1,2,3,5,6,7],
    'salary':[75000,80000,55000,58000,90000,100000],
    'bonus':[7000,4000,5000,6000,8000,9000]
}

employee=pd.DataFrame(emp)
salary=pd.DataFrame(sal)
print(employee,"\n\n",salary)

   employee_id      name department
0            1    Chetan         Hr
1            2    Prerna         IT
2            3  Lokendra    Finance
3            4     Nitin      Sales
4            5    Pranav  Marketing

    employee_id  salary  bonus
0            1   75000   7000
1            2   80000   4000
2            3   55000   5000
3            5   58000   6000
4            6   90000   8000
5            7  100000   9000

In [66]:
pd.merge(employee,salary) # yha pe woh hi merge ho rahi hai jo dono mai coommon hai

   employee_id      name department  salary  bonus
0            1    Chetan         Hr   75000   7000
1            2    Prerna         IT   80000   4000
2            3  Lokendra    Finance   55000   5000
3            5    Pranav  Marketing   58000   6000

In [67]:
# inner and outer merge
pd.merge(employee,salary,on='employee_id',how='inner')

   employee_id      name department  salary  bonus
0            1    Chetan         Hr   75000   7000
1            2    Prerna         IT   80000   4000
2            3  Lokendra    Finance   55000   5000
3            5    Pranav  Marketing   58000   6000

In [68]:
merded_df=pd.merge(employee,salary,on='employee_id',how='outer')
print(merded_df)
# here you will get all the employers and with the data and if any data is missing then there is null value NaN

   employee_id      name department    salary   bonus
0            1    Chetan         Hr   75000.0  7000.0
1            2    Prerna         IT   80000.0  4000.0
2            3  Lokendra    Finance   55000.0  5000.0
3            4     Nitin      Sales       NaN     NaN
4            5    Pranav  Marketing   58000.0  6000.0
5            6       NaN        NaN   90000.0  8000.0
6            7       NaN        NaN  100000.0  9000.0

In [69]:
# now replace null value by '___' 
values={
    'employee_id':00,
    'name':'unknown',
    'department':'NOT_found',
    'salary':'nil',
    'bonus':'Nil'
    
}
merded_df.fillna(value=values)

   employee_id      name department    salary   bonus
0            1    Chetan         Hr   75000.0  7000.0
1            2    Prerna         IT   80000.0  4000.0
2            3  Lokendra    Finance   55000.0  5000.0
3            4     Nitin      Sales       nil     Nil
4            5    Pranav  Marketing   58000.0  6000.0
5            6   unknown  NOT_found   90000.0  8000.0
6            7   unknown  NOT_found  100000.0  9000.0

In [70]:
pd.merge(employee,salary,on='employee_id',how='left')

   employee_id      name department   salary   bonus
0            1    Chetan         Hr  75000.0  7000.0
1            2    Prerna         IT  80000.0  4000.0
2            3  Lokendra    Finance  55000.0  5000.0
3            4     Nitin      Sales      NaN     NaN
4            5    Pranav  Marketing  58000.0  6000.0

In [71]:
pd.merge(employee,salary,on='employee_id',how='right')

   employee_id      name department  salary  bonus
0            1    Chetan         Hr   75000   7000
1            2    Prerna         IT   80000   4000
2            3  Lokendra    Finance   55000   5000
3            5    Pranav  Marketing   58000   6000
4            6       NaN        NaN   90000   8000
5            7       NaN        NaN  100000   9000

## now how to concatenate the two dataframes

In [72]:
import pandas as pd

df1 = pd.DataFrame({
    "ID": [101, 102, 103, 104],
    "Name": ["Priya", "Rahul", "Aman", "Chetan"],
    "Age": [20, 21, 22, 20],
    "City": ["Jaipur", "Delhi", "Indore", "SawaiMadhopur"],
    "Salary": [38000, 35000, 42000,50000 ]
})

df2 = pd.DataFrame({
    "ID": [105, 106, 107, 108],
    "Name": ["Prerna", "Rohit", "Anjali", "Vikas"],
    "Age": [20, 23, 21, 24],
    "City": ["Nepanagar", "Mumbai", "Pune", "Kota"],
    "Salary": [55000, 45000, 36000, 52000]
})



df3=pd.concat([df1,df2],ignore_index=True)
print(df3)

    ID    Name  Age           City  Salary
0  101   Priya   20         Jaipur   38000
1  102   Rahul   21          Delhi   35000
2  103    Aman   22         Indore   42000
3  104  Chetan   20  SawaiMadhopur   50000
4  105  Prerna   20      Nepanagar   55000
5  106   Rohit   23         Mumbai   45000
6  107  Anjali   21           Pune   36000
7  108   Vikas   24           Kota   52000

In [73]:
df4=pd.DataFrame({
    'Work-Location':['Remote','On-site','On-site','hybrid','Remote','hybrid','remote','remote'],
    'Department':['Cse','IT','Ec','Cse','IT','Cse','AI','Ec']
}
)


print(df4)

  Work-Location Department
0        Remote        Cse
1       On-site         IT
2       On-site         Ec
3        hybrid        Cse
4        Remote         IT
5        hybrid        Cse
6        remote         AI
7        remote         Ec

In [74]:
# concatenate df3 and df4
p=pd.concat([df3,df4],axis=1)
print(p)

    ID    Name  Age           City  Salary Work-Location Department
0  101   Priya   20         Jaipur   38000        Remote        Cse
1  102   Rahul   21          Delhi   35000       On-site         IT
2  103    Aman   22         Indore   42000       On-site         Ec
3  104  Chetan   20  SawaiMadhopur   50000        hybrid        Cse
4  105  Prerna   20      Nepanagar   55000        Remote         IT
5  106   Rohit   23         Mumbai   45000        hybrid        Cse
6  107  Anjali   21           Pune   36000        remote         AI
7  108   Vikas   24           Kota   52000        remote         Ec

In [75]:
# joining 2 data frames 
dfr1=pd.DataFrame({
    'name':['Chetan','Prerna','Lokendra','Nitin'],
},index=[1,2,3,4])

dfr2=pd.DataFrame({
    'ID':[101,102,104,105]
},index=[1,2,4,5])

dfr1.join(dfr2)

       name     ID
1    Chetan  101.0
2    Prerna  102.0
3  Lokendra    NaN
4     Nitin  104.0

In [76]:
dfr2.join(dfr1)

    ID    name
1  101  Chetan
2  102  Prerna
4  104   Nitin
5  105     NaN

In [77]:
dfr1.join(dfr2,how='outer')

       name     ID
1    Chetan  101.0
2    Prerna  102.0
3  Lokendra    NaN
4     Nitin  104.0
5       NaN  105.0

In [78]:
dfr2.join(dfr1,how='outer')

      ID      name
1  101.0    Chetan
2  102.0    Prerna
3    NaN  Lokendra
4  104.0     Nitin
5  105.0       NaN