In [43]:
import pandas as pd
import numpy as np

### finding the missing data in the table

In [44]:
data=[
    ['chetan',20,np.nan,100],
    ['prerna',19,'nepanagar',110],
    ['lokendra',np.nan,'orai',50],
    [np.nan,21,'bhilai',80],
    ['nitin',20,'bhatinda',np.nan],
    ['ronak',np.nan,'jodhpur',np.nan]
]

label=['A','B','C','D','E','F']
df=pd.DataFrame(data,index=label,columns=['Names','Age','City','Salary'])
print(df)
print()
print(df.isna())
print()
print(df.isna().sum())
print()
print(df.isna().any())

      Names   Age       City  Salary
A    chetan  20.0        NaN   100.0
B    prerna  19.0  nepanagar   110.0
C  lokendra   NaN       orai    50.0
D       NaN  21.0     bhilai    80.0
E     nitin  20.0   bhatinda     NaN
F     ronak   NaN    jodhpur     NaN

   Names    Age   City  Salary
A  False  False   True   False
B  False  False  False   False
C  False   True  False   False
D   True  False  False   False
E  False  False  False    True
F  False   True  False    True

Names     1
Age       2
City      1
Salary    2
dtype: int64

Names     True
Age       True
City      True
Salary    True
dtype: bool

In [45]:
# Remove the missing data

df.dropna() # this will drop the all rows having the null value nan

    Names   Age       City  Salary
B  prerna  19.0  nepanagar   110.0

In [46]:
df

      Names   Age       City  Salary
A    chetan  20.0        NaN   100.0
B    prerna  19.0  nepanagar   110.0
C  lokendra   NaN       orai    50.0
D       NaN  21.0     bhilai    80.0
E     nitin  20.0   bhatinda     NaN
F     ronak   NaN    jodhpur     NaN

In [47]:
# df.dropna(inplace=True)
# print(df)

In [49]:
df.dropna(thresh=3)
# matlb jis row mai atleast 3 se jyada non null values hai vo delete nahi hoga

      Names   Age       City  Salary
A    chetan  20.0        NaN   100.0
B    prerna  19.0  nepanagar   110.0
C  lokendra   NaN       orai    50.0
D       NaN  21.0     bhilai    80.0
E     nitin  20.0   bhatinda     NaN

In [ ]:
# filling the missing data