In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

## introduction to series
#### series is the 1d data
#### series is in the vertical format

In [2]:
labels=['a','b','c','d']
my_list=[10,20,30,40]
arr=np.array([100,200,300,400])
dic={1:1000,2:2000,3:3000,4:4000}

# now print the series 
print(pd.Series(my_list))
print("\n")
print(pd.Series(arr))
print("\n")


# if we want to add the custom lables 
print(pd.Series(arr,index=labels))

print()
print(pd.Series(dic))

0    10
1    20
2    30
3    40
dtype: int64


0    100
1    200
2    300
3    400
dtype: int64


a    100
b    200
c    300
d    400
dtype: int64

1    1000
2    2000
3    3000
4    4000
dtype: int64

In [3]:
tup=('chetan','cse2','prerna','it')
print(pd.Series(tup))

0    chetan
1      cse2
2    prerna
3        it
dtype: str

# DATAFRAME 
### DATAFRAME IS MADE UP OF MANY SERIES

In [4]:
data={
    'Names':['chetan','lokendra','abhay','nitin','ronak'],
    'Age': [20,21,21,20,17],
    'City':['sawaimadhopur','orai','bhilai','bhatinda','jodhpur'],
    'Salary':[10,5,8,9,7]
}

label=['A','B','C','D','E']

df=pd.DataFrame(data,index=label)
print(df)

      Names  Age           City  Salary
A    chetan   20  sawaimadhopur      10
B  lokendra   21           orai       5
C     abhay   21         bhilai       8
D     nitin   20       bhatinda       9
E     ronak   17        jodhpur       7

In [5]:
data2=[
    ['chetan',20,'sawaimadhopur',100],
    ['prerna',19,'nepanagar',110],
    ['lokendra',21,'orai',50],
    ['abhay',21,'bhilai',80],
    ['nitin',20,'bhatinda',90],
    ['ronak',17,'jodhpur',70]
]
label2=['A','B','C','D','E','F']

df2=pd.DataFrame(data2,index=label2,columns=['Names','Age','City','Salary'])
print(df2)


print()

data3=(
    ('chetan',20,'sawaimadhopur',100),
    ('prerna',19,'nepanagar',110),
    ('lokendra',21,'orai',50),
    ('abhay',21,'bhilai',80),
    ('nitin',20,'bhatinda',90),
    ('ronak',17,'jodhpur',70)
)

df3=pd.DataFrame(data3,index=label2,columns=['Names','Age','City','Salary'])
print(df3)

      Names  Age           City  Salary
A    chetan   20  sawaimadhopur     100
B    prerna   19      nepanagar     110
C  lokendra   21           orai      50
D     abhay   21         bhilai      80
E     nitin   20       bhatinda      90
F     ronak   17        jodhpur      70

      Names  Age           City  Salary
A    chetan   20  sawaimadhopur     100
B    prerna   19      nepanagar     110
C  lokendra   21           orai      50
D     abhay   21         bhilai      80
E     nitin   20       bhatinda      90
F     ronak   17        jodhpur      70

### slicing and indexing and selecting the data

In [6]:
print(type(df2))
print(df2['Names'])
print()

# if i want to select multiple columns

print(df2[['Names','City']])

<class 'pandas.DataFrame'>
A      chetan
B      prerna
C    lokendra
D       abhay
E       nitin
F       ronak
Name: Names, dtype: str

      Names           City
A    chetan  sawaimadhopur
B    prerna      nepanagar
C  lokendra           orai
D     abhay         bhilai
E     nitin       bhatinda
F     ronak        jodhpur

In [7]:
# inserting the columns in the data 

df2["Batch-Exp"]=2029
print(df2)

print()
df2.insert(2,"Gender",["Male","Female","Male","Male","Male","Male",])  # this insert the gender at the index 2 
print(df2)

      Names  Age           City  Salary  Batch-Exp
A    chetan   20  sawaimadhopur     100       2029
B    prerna   19      nepanagar     110       2029
C  lokendra   21           orai      50       2029
D     abhay   21         bhilai      80       2029
E     nitin   20       bhatinda      90       2029
F     ronak   17        jodhpur      70       2029

      Names  Age  Gender           City  Salary  Batch-Exp
A    chetan   20    Male  sawaimadhopur     100       2029
B    prerna   19  Female      nepanagar     110       2029
C  lokendra   21    Male           orai      50       2029
D     abhay   21    Male         bhilai      80       2029
E     nitin   20    Male       bhatinda      90       2029
F     ronak   17    Male        jodhpur      70       2029

In [8]:
# if we want to delete row or column 

print(df2.drop('F',axis=0)) # delete the row having index 'F'

print()

print(df2.drop('Batch-Exp',axis=1)) # delete the col having index 'Batch-Exp'

      Names  Age  Gender           City  Salary  Batch-Exp
A    chetan   20    Male  sawaimadhopur     100       2029
B    prerna   19  Female      nepanagar     110       2029
C  lokendra   21    Male           orai      50       2029
D     abhay   21    Male         bhilai      80       2029
E     nitin   20    Male       bhatinda      90       2029

      Names  Age  Gender           City  Salary
A    chetan   20    Male  sawaimadhopur     100
B    prerna   19  Female      nepanagar     110
C  lokendra   21    Male           orai      50
D     abhay   21    Male         bhilai      80
E     nitin   20    Male       bhatinda      90
F     ronak   17    Male        jodhpur      70

In [9]:
df2 # still the data remain same ...

      Names  Age  Gender           City  Salary  Batch-Exp
A    chetan   20    Male  sawaimadhopur     100       2029
B    prerna   19  Female      nepanagar     110       2029
C  lokendra   21    Male           orai      50       2029
D     abhay   21    Male         bhilai      80       2029
E     nitin   20    Male       bhatinda      90       2029
F     ronak   17    Male        jodhpur      70       2029

In [10]:
# we have to use the inplace=true 

df2.drop('F',axis=0,inplace=True)
df2.drop('Batch-Exp',axis=1,inplace=True)

print(df2)

      Names  Age  Gender           City  Salary
A    chetan   20    Male  sawaimadhopur     100
B    prerna   19  Female      nepanagar     110
C  lokendra   21    Male           orai      50
D     abhay   21    Male         bhilai      80
E     nitin   20    Male       bhatinda      90

### now selecting the data of the rows

In [11]:
# here we use loc for the rows to give the location of the rows
print(df2.loc['A'])
df2.loc[['A','B']]

Names            chetan
Age                  20
Gender             Male
City      sawaimadhopur
Salary              100
Name: A, dtype: object

    Names  Age  Gender           City  Salary
A  chetan   20    Male  sawaimadhopur     100
B  prerna   19  Female      nepanagar     110

In [12]:
''' if i want to select somee portion of the data table ...
'''
## select the names and city of people of row A,B
print(df2.loc[['A','B']][['Names','City']])

# select names age and city A,B
print("\n",df2.loc[['A','B']][['Names','Age','City']])

    Names           City
A  chetan  sawaimadhopur
B  prerna      nepanagar

     Names  Age           City
A  chetan   20  sawaimadhopur
B  prerna   19      nepanagar

In [13]:
df2[df2['Salary']<100] # select those whose salary<100 lpa

      Names  Age Gender      City  Salary
C  lokendra   21   Male      orai      50
D     abhay   21   Male    bhilai      80
E     nitin   20   Male  bhatinda      90

In [14]:
df2[df2['Salary']>=100] # select those whose salary>=100 lpa

    Names  Age  Gender           City  Salary
A  chetan   20    Male  sawaimadhopur     100
B  prerna   19  Female      nepanagar     110

In [15]:
# i want to select the peoples whose salary<100 and age>20
df2[(df2['Salary']<100) & (df2['Age']==20)]

   Names  Age Gender      City  Salary
E  nitin   20   Male  bhatinda      90