In [8]:
import pandas as pd
import numpy as np

Pivot Tables

In [9]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
           'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

pd.DataFrame(data)

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    152     53   John
1  2023-01-02       B   West    103     28   Mary
2  2023-01-03       C  North    336     73    Bob
3  2023-01-04       D  South    202     30  Alice
4  2023-01-05       A   East    861     38   John
5  2023-01-06       B   West    587     74   Mary
6  2023-01-07       C  North    953     81    Bob
7  2023-01-08       D  South    635     37  Alice
8  2023-01-09       A   East    543     78   John
9  2023-01-10       B   West    276     45   Mary
10 2023-01-11       C  North    432     73    Bob
11 2023-01-12       D  South    716     43  Alice
12 2023-01-13       A   East    242     11   John
13 2023-01-14       B   West    496     76   Mary
14 2023-01-15       C  North    150     55    Bob
15 2023-01-16       D  South    276     76  Alice
16 2023-01-17       A   East    893     31   John
17 2023-01-18       B   West    937     75   Mary
18 2023-01-19       C  North    436     22    Bob
19 2023-01-20       D  South    584     83  Alice

In [12]:
df=pd.DataFrame(data)
print(df)

df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    152     53   John
1  2023-01-02       B   West    103     28   Mary
2  2023-01-03       C  North    336     73    Bob
3  2023-01-04       D  South    202     30  Alice
4  2023-01-05       A   East    861     38   John
5  2023-01-06       B   West    587     74   Mary
6  2023-01-07       C  North    953     81    Bob
7  2023-01-08       D  South    635     37  Alice
8  2023-01-09       A   East    543     78   John
9  2023-01-10       B   West    276     45   Mary
10 2023-01-11       C  North    432     73    Bob
11 2023-01-12       D  South    716     43  Alice
12 2023-01-13       A   East    242     11   John
13 2023-01-14       B   West    496     76   Mary
14 2023-01-15       C  North    150     55    Bob
15 2023-01-16       D  South    276     76  Alice
16 2023-01-17       A   East    893     31   John
17 2023-01-18       B   West    937     75   Mary
18 2023-01-19       C  North    436     22    Bob
19 2023-01-20       D  South    584     83  Alice

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    152     53   John  January      Q1
1  2023-01-02       B   West    103     28   Mary  January      Q1
2  2023-01-03       C  North    336     73    Bob  January      Q1
3  2023-01-04       D  South    202     30  Alice  January      Q1
4  2023-01-05       A   East    861     38   John  January      Q1
5  2023-01-06       B   West    587     74   Mary  January      Q1
6  2023-01-07       C  North    953     81    Bob  January      Q1
7  2023-01-08       D  South    635     37  Alice  January      Q1
8  2023-01-09       A   East    543     78   John  January      Q1
9  2023-01-10       B   West    276     45   Mary  January      Q1
10 2023-01-11       C  North    432     73    Bob  January      Q1
11 2023-01-12       D  South    716     43  Alice  January      Q1
12 2023-01-13       A   East    242     11   John  January      Q1
13 2023-01-14       B   West    496     76   Mary  January      Q1
14 2023-01-15       C  North    150     55    Bob  January      Q1
15 2023-01-16       D  South    276     76  Alice  January      Q1
16 2023-01-17       A   East    893     31   John  January      Q1
17 2023-01-18       B   West    937     75   Mary  January      Q1
18 2023-01-19       C  North    436     22    Bob  January      Q1
19 2023-01-20       D  South    584     83  Alice  January      Q1

In [15]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     538.2    NaN    NaN    NaN
North      NaN    NaN  461.4    NaN
South      NaN    NaN    NaN  482.6
West       NaN  479.8    NaN    NaN

In [17]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='sum')    # here agg function is sum it gives the total sales in the particular region for the particular product

Product       A       B       C       D
Region
East     2691.0     NaN     NaN     NaN
North       NaN     NaN  2307.0     NaN
South       NaN     NaN     NaN  2413.0
West        NaN  2399.0     NaN     NaN