In [3]:
import pandas as pd
import numpy as np

### Pivot Tables and aggregation functions AND cross tab

In [4]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
           'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

pd.DataFrame(data)

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    679     50   John
1  2023-01-02       B   West    536     20   Mary
2  2023-01-03       C  North    945     29    Bob
3  2023-01-04       D  South    155     57  Alice
4  2023-01-05       A   East    931     57   John
5  2023-01-06       B   West    328     26   Mary
6  2023-01-07       C  North    445     26    Bob
7  2023-01-08       D  South    957     15  Alice
8  2023-01-09       A   East    470     72   John
9  2023-01-10       B   West    546     23   Mary
10 2023-01-11       C  North    760     17    Bob
11 2023-01-12       D  South    321     66  Alice
12 2023-01-13       A   East    974     19   John
13 2023-01-14       B   West    746     94   Mary
14 2023-01-15       C  North    944     80    Bob
15 2023-01-16       D  South    178     60  Alice
16 2023-01-17       A   East    223     99   John
17 2023-01-18       B   West    763     42   Mary
18 2023-01-19       C  North    180     80    Bob
19 2023-01-20       D  South    607     18  Alice

In [5]:
df=pd.DataFrame(data)
print(df)

df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    679     50   John
1  2023-01-02       B   West    536     20   Mary
2  2023-01-03       C  North    945     29    Bob
3  2023-01-04       D  South    155     57  Alice
4  2023-01-05       A   East    931     57   John
5  2023-01-06       B   West    328     26   Mary
6  2023-01-07       C  North    445     26    Bob
7  2023-01-08       D  South    957     15  Alice
8  2023-01-09       A   East    470     72   John
9  2023-01-10       B   West    546     23   Mary
10 2023-01-11       C  North    760     17    Bob
11 2023-01-12       D  South    321     66  Alice
12 2023-01-13       A   East    974     19   John
13 2023-01-14       B   West    746     94   Mary
14 2023-01-15       C  North    944     80    Bob
15 2023-01-16       D  South    178     60  Alice
16 2023-01-17       A   East    223     99   John
17 2023-01-18       B   West    763     42   Mary
18 2023-01-19       C  North    180     80    Bob
19 2023-01-20       D  South    607     18  Alice

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    679     50   John  January      Q1
1  2023-01-02       B   West    536     20   Mary  January      Q1
2  2023-01-03       C  North    945     29    Bob  January      Q1
3  2023-01-04       D  South    155     57  Alice  January      Q1
4  2023-01-05       A   East    931     57   John  January      Q1
5  2023-01-06       B   West    328     26   Mary  January      Q1
6  2023-01-07       C  North    445     26    Bob  January      Q1
7  2023-01-08       D  South    957     15  Alice  January      Q1
8  2023-01-09       A   East    470     72   John  January      Q1
9  2023-01-10       B   West    546     23   Mary  January      Q1
10 2023-01-11       C  North    760     17    Bob  January      Q1
11 2023-01-12       D  South    321     66  Alice  January      Q1
12 2023-01-13       A   East    974     19   John  January      Q1
13 2023-01-14       B   West    746     94   Mary  January      Q1
14 2023-01-15       C  North    944     80    Bob  January      Q1
15 2023-01-16       D  South    178     60  Alice  January      Q1
16 2023-01-17       A   East    223     99   John  January      Q1
17 2023-01-18       B   West    763     42   Mary  January      Q1
18 2023-01-19       C  North    180     80    Bob  January      Q1
19 2023-01-20       D  South    607     18  Alice  January      Q1

In [6]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     655.4    NaN    NaN    NaN
North      NaN    NaN  654.8    NaN
South      NaN    NaN    NaN  443.6
West       NaN  583.8    NaN    NaN

In [7]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='sum')    # here agg function is sum it gives the total sales in the particular region for the particular product

Product       A       B       C       D
Region
East     3277.0     NaN     NaN     NaN
North       NaN     NaN  3274.0     NaN
South       NaN     NaN     NaN  2218.0
West        NaN  2919.0     NaN     NaN

In [11]:
# multivalues pivot table 
pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product',aggfunc='mean')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     655.4    NaN    NaN    NaN  59.4   NaN   NaN   NaN
North      NaN    NaN  654.8    NaN   NaN   NaN  46.4   NaN
South      NaN    NaN    NaN  443.6   NaN   NaN   NaN  43.2
West       NaN  583.8    NaN    NaN   NaN  41.0   NaN   NaN

In [13]:
# cross tab ----it is used for the counting purpose 
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0